---
apiVersion: v1
kind: Namespace
metadata:
  name: virtual-machines
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-bridge
spec:
  config: | #json
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "vmbr0",
      "disableContainerInterface": true,
      "macspoofchk": true
    }
