---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
spec:
  project: default
  sources:
    - chart: victoria-metrics-k8s-stack
      repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.72.2
      helm:
        valueFiles:
          - $values/k8s/victoria-metrics/values.yaml
    - repoURL: https://github.com/tillycode/homelab-v2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
  ignoreDifferences:
    - kind: Secret
      name: victoria-metrics-victoria-metrics-operator-validation
      namespace: victoria-metrics
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-victoria-metrics-operator-admission
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
spec:
  project: default
  sources:
    - chart: grafana-operator
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 5.22.0
      helm:
        valueFiles:
          - $values/k8s/grafana-operator/values.yaml
    - repoURL: https://github.com/tillycode/homelab-v2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: default
  source:
    repoURL: https://github.com/tillycode/homelab-v2.git
    targetRevision: main
    path: k8s/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
spec:
  project: default
  sources:
    - chart: victoria-logs-cluster
      repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.0.29
      helm:
        valueFiles:
          - $values/k8s/victoria-logs/values.yaml
    - repoURL: https://github.com/tillycode/homelab-v2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-logs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
spec:
  project: default
  sources:
    - chart: vector
      repoURL: https://helm.vector.dev
      targetRevision: 0.52.0
      helm:
        valueFiles:
          - $values/k8s/vector/values.yaml
    - repoURL: https://github.com/tillycode/homelab-v2.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vector
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
