apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
  - route.yaml

patches:
  - path: configmaps.yaml
  - patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups: [""]
          resources: ["pods/exec"]
          verbs: ["create"]
    target:
      kind: ClusterRole
      name: argocd-server
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: argocd-redis-ha-haproxy
      spec:
       strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 25%
