name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.szp.io
            extra-trusted-public-keys = cache.szp.io-1:5ka/6qZ6Gg8/zeUWwglEvQIP1d1a1yzMgGmwBkqNb7Y=
            experimental-features = nix-command flakes local-overlay-store
      - uses: actions/cache@v5
        with:
          path: /tmp/nix-store/lower
          key: nix-store-${{ hashFiles('flake.lock') }}
          restore-keys: nix-store-
      - run: |
          sudo /nix/var/nix/profiles/default/bin/nix copy --all --from /tmp/nix-store/lower
